node:
  build: ./node
  volumes:
    # - "./node:/src/node"
    # Mount local dir for development
    - "./node:/usr/src/app"
  ports:
    - "80:3000"
  links:
   - redis


redis:
  image: redis
  # build: ./redis
  ports:
    - "6379:6379"

worker:
  build: ./node
  volumes:
    - "./node:/usr/src/app"
  links:
    - redis
  command: npm run cron

# worker:
#   build: .
#   links:
#     - redis:redisdb
#   command: jobs
#   volumes_from:
#     - app
#   environment:
#     SECRET_KEY_BASE: much_security
